<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE texto [
  <!ELEMENT texto ((#PCDATA | parrafo), titulo)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT parrafo (#PCDATA | abreviatura)>
  <!ELEMENT abreviatura (#PCDATA)>
]>

<texto>
<titulo>XML explicado a los niños</titulo>
<parrafo>El <abreviatura>XML</abreviatura>define cómo crear lenguajes de marcas.
</parrafo>
<parrafo>Las marcas se añaden a un documento de texto para añadir información.</parrafo>
 http://www.example.org/http://
</texto>