=== victorfernandezesp/victorfernandezesp.github.io/lm/unidad6/libros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="libros">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="libro" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="titulo" type="xs:string"/>
                        <xs:element name="fechaPubli" type="xs:date"/>
                        <xs:element name="ref" type="xs:string"/>

                        <xs:element name="precio">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:decimal">
                                        <xs:attribute name="divisa" default="â‚¬" use="optional"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="disponible" type="xs:boolean" default="true" use="optional" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== victorfernandezesp/victorfernandezesp.github.io/lm/unidad6/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="libros.xsd" >
    <libro disponible="true">
        <titulo>The Elements</titulo>
        <fechaPubli>2000-11-24</fechaPubli>
        <ref>23-TE</ref>
        <precio>12.45</precio>
    </libro>
    <libro disponible="true">
        <titulo>Alquimia</titulo>
        <fechaPubli>1988-01-02</fechaPubli>
        <ref>13-Al</ref>
        <precio divisa="$">25.24</precio>
    </libro>
    <libro disponible="false">
        <titulo>El Médico</titulo>
        <fechaPubli>2007-07-30</fechaPubli>
        <ref>09-EM</ref>
        <precio divisa="€">30.12</precio>
    </libro>   
</libros>
