=== victorfernandezesp/victorfernandezesp.github.io/lm/unidad6/repaso3.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT deportistas (deportista+)>
<!ELEMENT deportista (deporte+, nombre)>
<!ELEMENT deporte (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>

=== victorfernandezesp/victorfernandezesp.github.io/lm/unidad6/repaso3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas SYSTEM "repaso3.dtd">
<deportistas>
  <deportista>
    <deporte> Atletismo </deporte>
    <nombre>Jesse Owens</nombre>
   </deportista>

  <deportista>
    <deporte> Natación </deporte>
    <deporte> Ciclismo </deporte>
    <nombre>Mark Spitz</nombre>
  </deportista>
</deportistas>
